name: Lint

# Controls when the action will run. 
on: push 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Intalls project dependencies
      - name: Install Node Modules
        run: npm i --ci

      # Runs ESLint
      - name: Run ESLint
        run: npm run lint
